import { FunctionComponent, ReactNode } from "react";
import type { Metadata } from "next";
import { SpartanFont } from "@/styles/fonts";
import ThemesProvider from "@/providers/ThemesProvider";
import TanstackProvider from "@/providers/TanstackProvider";
// import DefaultLayout from "@/layout/Default";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/main-icon.svg",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FunctionComponent<RootLayoutProps> = ({ children }) => {
  return (
    <TanstackProvider>
      <ThemesProvider>
        <html lang="en">
          <body className={SpartanFont.className}>
            {/* <DefaultLayout>{children}</DefaultLayout> */}
            {children}
          </body>
        </html>
      </ThemesProvider>
    </TanstackProvider>
  );
};

export default RootLayout;

// "use client";

// import { FunctionComponent, ReactNode } from "react";
// import styled from "styled-components";
// import Navbar from "@/layout/Navbar";

// interface DefaultLayoutProps {
//   children: ReactNode;
// }

// const DefaultLayout: FunctionComponent<DefaultLayoutProps> = ({ children }) => {
//   return (
//     <DefaultLayoutStyles>
//       <div className="navbar">
//         <Navbar />
//       </div>
//       <div className="content">{children}</div>
//     </DefaultLayoutStyles>
//   );
// };

// const DefaultLayoutStyles = styled.div`
//   .navbar {
//     position: fixed;
//     top: 0;
//     left: 0;
//     right: 0;
//     z-index: 6;

//     @media (min-width: 1440px) {
//       right: calc(100vw - 6.43rem);
//       left: 0;
//       top: 0;
//       bottom: 0;
//     }
//   }

//   .content {
//     padding-top: 4.5rem;

//     @media (min-width: 768px) {
//       padding-top: 5rem;
//     }

//     @media (min-width: 1440px) {
//       padding-top: 0;
//       padding-left: 6.43rem;
//     }
//   }
// `;

// export default DefaultLayout;
