import { FunctionComponent, ReactNode } from "react";
import type { Metadata } from "next";
import { SpartanFont } from "@/styles/fonts";
import ThemesProvider from "@/providers/ThemesProvider";
import TanstackProvider from "@/providers/TanstackProvider";
import DefaultLayout from "@/layout/Default";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/main-icon.svg",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FunctionComponent<RootLayoutProps> = ({ children }) => {
  return (
    <TanstackProvider>
      <ThemesProvider>
        <html lang="en">
          <body className={SpartanFont.className}>
            <DefaultLayout>{children}</DefaultLayout>
          </body>
        </html>
      </ThemesProvider>
    </TanstackProvider>
  );
};

export default RootLayout;
