import type { Metadata } from 'next'
import ThemesProvider from '@/providers/themes'
import { FunctionComponent, ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode,
}

const RootLayout: FunctionComponent<RootLayoutProps> =({ children }) => {
  return (
    <ThemesProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </ThemesProvider>
  )
}

export default RootLayout;